/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	rokibulhasanv1alpha1 "github.com/RokibulHasan7/crd/pkg/apis/rokibul.hasan/v1alpha1"
	versioned "github.com/RokibulHasan7/crd/pkg/client/clientset/versioned"
	internalinterfaces "github.com/RokibulHasan7/crd/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/RokibulHasan7/crd/pkg/client/listers/rokibul.hasan/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RokibulHasanInformer provides access to a shared informer and lister for
// RokibulHasans.
type RokibulHasanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RokibulHasanLister
}

type rokibulHasanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRokibulHasanInformer constructs a new informer for RokibulHasan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRokibulHasanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRokibulHasanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRokibulHasanInformer constructs a new informer for RokibulHasan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRokibulHasanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RokibulV1alpha1().RokibulHasans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.RokibulV1alpha1().RokibulHasans(namespace).Watch(context.TODO(), options)
			},
		},
		&rokibulhasanv1alpha1.RokibulHasan{},
		resyncPeriod,
		indexers,
	)
}

func (f *rokibulHasanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRokibulHasanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *rokibulHasanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&rokibulhasanv1alpha1.RokibulHasan{}, f.defaultInformer)
}

func (f *rokibulHasanInformer) Lister() v1alpha1.RokibulHasanLister {
	return v1alpha1.NewRokibulHasanLister(f.Informer().GetIndexer())
}
