/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/RokibulHasan7/crd/pkg/apis/rokibul.hasan/v1alpha1"
	rokibulhasanv1alpha1 "github.com/RokibulHasan7/crd/pkg/client/applyconfiguration/rokibul.hasan/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRokibulHasans implements RokibulHasanInterface
type FakeRokibulHasans struct {
	Fake *FakeRokibulV1alpha1
	ns   string
}

var rokibulhasansResource = v1alpha1.SchemeGroupVersion.WithResource("rokibulhasans")

var rokibulhasansKind = v1alpha1.SchemeGroupVersion.WithKind("RokibulHasan")

// Get takes name of the rokibulHasan, and returns the corresponding rokibulHasan object, and an error if there is any.
func (c *FakeRokibulHasans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RokibulHasan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rokibulhasansResource, c.ns, name), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// List takes label and field selectors, and returns the list of RokibulHasans that match those selectors.
func (c *FakeRokibulHasans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RokibulHasanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rokibulhasansResource, rokibulhasansKind, c.ns, opts), &v1alpha1.RokibulHasanList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RokibulHasanList{ListMeta: obj.(*v1alpha1.RokibulHasanList).ListMeta}
	for _, item := range obj.(*v1alpha1.RokibulHasanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested rokibulHasans.
func (c *FakeRokibulHasans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rokibulhasansResource, c.ns, opts))

}

// Create takes the representation of a rokibulHasan and creates it.  Returns the server's representation of the rokibulHasan, and an error, if there is any.
func (c *FakeRokibulHasans) Create(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.CreateOptions) (result *v1alpha1.RokibulHasan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rokibulhasansResource, c.ns, rokibulHasan), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// Update takes the representation of a rokibulHasan and updates it. Returns the server's representation of the rokibulHasan, and an error, if there is any.
func (c *FakeRokibulHasans) Update(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (result *v1alpha1.RokibulHasan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rokibulhasansResource, c.ns, rokibulHasan), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRokibulHasans) UpdateStatus(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (*v1alpha1.RokibulHasan, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rokibulhasansResource, "status", c.ns, rokibulHasan), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// Delete takes name of the rokibulHasan and deletes it. Returns an error if one occurs.
func (c *FakeRokibulHasans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(rokibulhasansResource, c.ns, name, opts), &v1alpha1.RokibulHasan{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRokibulHasans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rokibulhasansResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RokibulHasanList{})
	return err
}

// Patch applies the patch and returns the patched rokibulHasan.
func (c *FakeRokibulHasans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RokibulHasan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rokibulhasansResource, c.ns, name, pt, data, subresources...), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied rokibulHasan.
func (c *FakeRokibulHasans) Apply(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error) {
	if rokibulHasan == nil {
		return nil, fmt.Errorf("rokibulHasan provided to Apply must not be nil")
	}
	data, err := json.Marshal(rokibulHasan)
	if err != nil {
		return nil, err
	}
	name := rokibulHasan.Name
	if name == nil {
		return nil, fmt.Errorf("rokibulHasan.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rokibulhasansResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeRokibulHasans) ApplyStatus(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error) {
	if rokibulHasan == nil {
		return nil, fmt.Errorf("rokibulHasan provided to Apply must not be nil")
	}
	data, err := json.Marshal(rokibulHasan)
	if err != nil {
		return nil, err
	}
	name := rokibulHasan.Name
	if name == nil {
		return nil, fmt.Errorf("rokibulHasan.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rokibulhasansResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.RokibulHasan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.RokibulHasan), err
}
