/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/RokibulHasan7/crd/pkg/apis/rokibul.hasan/v1alpha1"
	rokibulhasanv1alpha1 "github.com/RokibulHasan7/crd/pkg/client/applyconfiguration/rokibul.hasan/v1alpha1"
	scheme "github.com/RokibulHasan7/crd/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// RokibulHasansGetter has a method to return a RokibulHasanInterface.
// A group's client should implement this interface.
type RokibulHasansGetter interface {
	RokibulHasans(namespace string) RokibulHasanInterface
}

// RokibulHasanInterface has methods to work with RokibulHasan resources.
type RokibulHasanInterface interface {
	Create(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.CreateOptions) (*v1alpha1.RokibulHasan, error)
	Update(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (*v1alpha1.RokibulHasan, error)
	UpdateStatus(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (*v1alpha1.RokibulHasan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.RokibulHasan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.RokibulHasanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RokibulHasan, err error)
	Apply(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error)
	ApplyStatus(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error)
	RokibulHasanExpansion
}

// rokibulHasans implements RokibulHasanInterface
type rokibulHasans struct {
	client rest.Interface
	ns     string
}

// newRokibulHasans returns a RokibulHasans
func newRokibulHasans(c *RokibulV1alpha1Client, namespace string) *rokibulHasans {
	return &rokibulHasans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the rokibulHasan, and returns the corresponding rokibulHasan object, and an error if there is any.
func (c *rokibulHasans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.RokibulHasan, err error) {
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of RokibulHasans that match those selectors.
func (c *rokibulHasans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RokibulHasanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.RokibulHasanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("rokibulhasans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested rokibulHasans.
func (c *rokibulHasans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("rokibulhasans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a rokibulHasan and creates it.  Returns the server's representation of the rokibulHasan, and an error, if there is any.
func (c *rokibulHasans) Create(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.CreateOptions) (result *v1alpha1.RokibulHasan, err error) {
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("rokibulhasans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rokibulHasan).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a rokibulHasan and updates it. Returns the server's representation of the rokibulHasan, and an error, if there is any.
func (c *rokibulHasans) Update(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (result *v1alpha1.RokibulHasan, err error) {
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(rokibulHasan.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rokibulHasan).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *rokibulHasans) UpdateStatus(ctx context.Context, rokibulHasan *v1alpha1.RokibulHasan, opts v1.UpdateOptions) (result *v1alpha1.RokibulHasan, err error) {
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(rokibulHasan.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(rokibulHasan).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the rokibulHasan and deletes it. Returns an error if one occurs.
func (c *rokibulHasans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *rokibulHasans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("rokibulhasans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched rokibulHasan.
func (c *rokibulHasans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.RokibulHasan, err error) {
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied rokibulHasan.
func (c *rokibulHasans) Apply(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error) {
	if rokibulHasan == nil {
		return nil, fmt.Errorf("rokibulHasan provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rokibulHasan)
	if err != nil {
		return nil, err
	}
	name := rokibulHasan.Name
	if name == nil {
		return nil, fmt.Errorf("rokibulHasan.Name must be provided to Apply")
	}
	result = &v1alpha1.RokibulHasan{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *rokibulHasans) ApplyStatus(ctx context.Context, rokibulHasan *rokibulhasanv1alpha1.RokibulHasanApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.RokibulHasan, err error) {
	if rokibulHasan == nil {
		return nil, fmt.Errorf("rokibulHasan provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(rokibulHasan)
	if err != nil {
		return nil, err
	}

	name := rokibulHasan.Name
	if name == nil {
		return nil, fmt.Errorf("rokibulHasan.Name must be provided to Apply")
	}

	result = &v1alpha1.RokibulHasan{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("rokibulhasans").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
